o chiktuku  cd c:\Users\HALIME\habit\habit\habit\android ; .\gradlew.bat clean ; .\gradlew.bat --no-daemon tasks 2>&1 Starting a Gradle Daemon (subsequent builds will be faster) <-------------> 0% INITIALIZING [2m 55s]
> Configure project :shared_preferences_android
e: file:///C:/Users/HALIME/AppData/Local/Pub/Cache/hosted/pub.dev/shared_preferences_android-2.4.23/android/build.gradle.kts:36:1: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public fun DependencyHandler.kotlin(module: String, version: String? = ...): Any defined in org.gradle.kotlin.dsl
public fun PluginDependenciesSpec.kotlin(module: String): PluginDependencySpec defined in org.gradle.kotlin.dsl
e: file:///C:/Users/HALIME/AppData/Local/Pub/Cache/hosted/pub.dev/shared_preferences_android-2.4.23/android/build.gradle.kts:37:5: Unresolved reference: compilerOptions
e: file:///C:/Users/HALIME/AppData/Local/Pub/Cache/hosted/pub.dev/shared_preferences_android-2.4.23/android/build.gradle.kts:38:9: Unresolved reference: jvmTarget

[Incubating] Problems report is available at: file:///C:/Users/HALIME/habit/habit/habit/android/build/reports/problems/problems-report.html

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\HALIME\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences_android-2.4.23\android\build.gradle.kts' line: 36

* What went wrong:
Script compilation errors:

  Line 36: kotlin {
           ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
               public fun DependencyHandler.kotlin(module: String, version: String? = ...): Any defined in org.gradle.kotlin.dsl
               public fun PluginDependenciesSpec.kotlin(module: String): PluginDependencySpec defined in org.gradle.kotlin.dsl

  Line 37:     compilerOptions {
               ^ Unresolved reference: compilerOptions

  Line 38:         jvmTarget = JvmTarget.fromTarget(JavaVersion.VERSION_17.toString())
                   ^ Unresolved reference: jvmTarget

3 errors

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.14/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 12m 54s
4 actionable tasks: 4 up-to-date
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.14/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build

> Configure project :shared_preferences_android

[Incubating] Problems report is available at: file:///C:/Users/HALIME/habit/habit/habit/android/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.14/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
4 actionable tasks: 4 up-to-date
.\gradlew.bat : e: file:///C:/Users/HALIME/AppData/Local/Pub/Cache/hosted/pub.dev/shared_preferences_android-2.4.23/android/build.gradle.kts:36:1: Unresolved reference. None o
f the following candidates is applicable because of receiver type mismatch:
At line:1 char:70
+ ... \android ; .\gradlew.bat clean ; .\gradlew.bat --no-daemon tasks 2>&1
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (e: file:///C:/U...type mismatch: :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

public fun DependencyHandler.kotlin(module: String, version: String? = ...): Any defined in org.gradle.kotlin.dsl
public fun PluginDependenciesSpec.kotlin(module: String): PluginDependencySpec defined in org.gradle.kotlin.dsl
e: file:///C:/Users/HALIME/AppData/Local/Pub/Cache/hosted/pub.dev/shared_preferences_android-2.4.23/android/build.gradle.kts:37:5: Unresolved reference: compilerOptions
e: file:///C:/Users/HALIME/AppData/Local/Pub/Cache/hosted/pub.dev/shared_preferences_android-2.4.23/android/build.gradle.kts:38:9: Unresolved reference: jvmTarget
FAILURE: Build failed with an exception.
* Where:
Build file 'C:\Users\HALIME\AppData\Local\Pub\Cache\hosted\pub.dev\shared_preferences_android-2.4.23\android\build.gradle.kts' line: 36
* What went wrong:
Script compilation errors:
  Line 36: kotlin {
           ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
               public fun DependencyHandler.kotlin(module: String, version: String? = ...): Any defined in org.gradle.kotlin.dsl
               public fun PluginDependenciesSpec.kotlin(module: String): PluginDependencySpec defined in org.gradle.kotlin.dsl
  Line 37:     compilerOptions {
               ^ Unresolved reference: compilerOptions
  Line 38:         jvmTarget = JvmTarget.fromTarget(JavaVersion.VERSION_17.toString())
                   ^ Unresolved reference: jvmTarget
3 errors
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 9m 58s
PS C:\Users\HALIME\habit\habit\habit\android>